#!/bin/bash
# Script to generate bifurcations
# arguments to give
# $1 SNR
# $2 nrImages
# default diameters are 3, 5 and 7 pixels
# this call is actually a wrapper for java call just that 3 parameters will take default values

EXPECTED_ARGS=2

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` SNR NrImages"
  exit $E_BADARGS
fi

# java call args: minSNR($1)  D1  D2  D3 nrImages($2)
java -cp critpoint_.jar:ij.jar:imagescience.jar generate.GeneratorDemo   $1   3 5 7    $2

echo "finished"

exit
