#!/bin/bash
# Script to generate bifurcations

# $1 SNR
# $2 nrImages

# java call args: minSNR  D1  D2  D3    nrImages
java -cp critpoint_.jar:ij.jar:imagescience.jar generate.GeneratorDemo   $1   3 5 7    $2

echo "finished"

exit